import type { Metadata } from "next";
import { Roboto_Slab, Inter } from 'next/font/google';
import "./globals.css";

const slab = Roboto_Slab({ subsets: ['latin'], weight: ['700', '900'] });
const sans = Inter({ subsets: ['latin'], weight: ['400', '600'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={sans.className}>
      <body>{children}</body>
    </html>
  );
}
